apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.nameOverride }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.nameOverride }}
  template:
    metadata:
      labels:
        app: {{ .Values.nameOverride }}
    spec:
      containers:
        - name: {{ .Values.nameOverride }}
          image: '{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest"}}'
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: webapp
              mountPath: /usr/local/tomcat/webapps/ROOT
      volumes:
        - name: webapp
          emptyDir: {}
