apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nameOverride }}-service
spec:
  selector:
    app: {{ .Values.nameOverride }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30000  # Specific nodePort for HTTP traffic
  type: NodePort
