name: Build and Push Image

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Enter the new version'
        required: true


jobs:
  build-and-push:
    runs-on:  self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read current version
        id: read-version
        run: |
          echo "::set-output name=initial_version::1.0.2"  # Initial version placeholder

      - name: Bump version
        id: bump-version
        run: |
          NEW_VERSION=${{ inputs.version }}
          echo $NEW_VERSION > version.txt
          echo "::set-output name=new_version::$NEW_VERSION"

      - name: Build and push Docker image
        run: |
          NEW_VERSION=${{ steps.bump-version.outputs.new_version }}
          kp image create tomcat-demo-${NEW_VERSION} \
            --namespace default \
            --builder my-builder \
            --tag dshep15/tomcat-demo:${NEW_VERSION} \
            --git https://github.com/DanielShepelev/tsassignment/ \
            --git-revision main

      - name: Update Helm Chart
        run: |
          NEW_VERSION=${{ steps.bump-version.outputs.new_version }}
          sed -i 's#dshep15/tomcat-demo:[0-9].[0-9].[0-9]#dshep15/tomcat-demo:'"$NEW_VERSION"'#g' helmfiles/templates/Deployment.yaml
          cat path/to/Deployment.yaml  # Confirm changes
